let atext= " dharshini priya";
let len= atext.length;
console.log("the string length is "+len);
let half= atext.slice(-3);
let hal= atext.slice(3);
let ha= atext.slice(12);
console.log(half);
console.log(hal);
console.log(ha);
let rep=atext.replace('dharshini','krishna');
console.log(rep);